
heat_template_version: 2016-10-14
description: spawning a custom web server

parameters:
  image_name:
    type: string
    default: my_image
  instance1_name:
    type: string
    default: my_inst1
  instance2_name:
    type: string
    default: my_inst2
  key_name:
    type: string
    default: my_key
  instance_flavor:
    type: string
    default: m1.small
  private_net:
    type: string
    default: private
    description: Name of private network into which servers get deployed
  private_subnet:
    type: string
    default: private_subnet
    description: Name of private subnet into which servers get deployed
resources:

  web_server1:
    type: OS::Nova::Server
    properties:
      name: { get_param: instance1_name }
      image: { get_param: image_name }
      flavor: { get_param: instance_flavor }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: my_net_port1 }
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            echo "hello" > /etc/motd 
            echo "my private ip is $private_ip" >> /etc/motd 
          params:
            $private_ip: { get_attr: [ my_net_port1, fixed_ips, 0, ip_address ] }

  my_net_port1:
    type: OS::Neutron::Port
    properties:
      network: { get_param: private_net }
      fixed_ips:
        - subnet: { get_param: private_subnet }

            
